name: check-build-actions

on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
          run:
            working-directory: ./front-end

    steps:
      - uses: actions/checkout@v3
        
      - name: next install and Build
        run: |
          npm install
          npm run build --if-present
          
    
