name: check-build-actions

on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #       run:
    #         working-directory: mvp-frontend/front-end

    steps:
      - uses: actions/checkout@v3
        
      - name: Move and Install
        run: |
          cd mvp-frontend/front-end/
          npm install  
      - name: Build
        run: |
          cd mvp-frontend/front-end/
          npm run build --if-present
    
